### ISSUE TITLE
Missing controller code

### ISSUE THREAD

**Issue by scott2b** [poderopedia/plug-and-play-1.0-RC#20]
The following controllers / functions have navigational elements in the views, yet seem to be missing from the code. Is there a plan to include these in the source?

directorio/general (controller, with functions: persona, empresa, organazacion)

also:

personas/mapa_relaciones

**Comment by juaneduardo** [comment]
Hi Scott...  you're checking the template_app? 
Directorio (general, empresa an organizacion) renders a default view that call another components
The same for personas/mapa_relaciones

Have you experienced a problem in the render of the views?

**Comment by scott2b** [comment]
Oh ok, I was looking in the admin_app. I see that the code I was looking for is in template_app. However, that is not where the navigation leads me. E.g. if I click the View button for a person in the admin app, the person's page comes up, but the navigation in the header (A-Z, personas, empresas, organazaciones) point to locations under admin_app, not template_app.

**Comment by juaneduardo** [comment]
Scott Please check the updated version.
Feel free to send me any issue.
Thanks

**Comment by scott2b** [comment]
Yes. So, my template_app controllers and some admin_app controllers are not working at the moment -- but that is a whole other thing I need to look into. The navigation in the header bar however is now correct. Thanks!

There still seem to be navigational issues with some of the sub-navigation on the person page. In particular: the "Mapa de Relaciones" tab as well as the sub-navs: "sugerir conexiones" and "requiere actualizacion" do not point to valid controllers/functions.

Thank you!

**Comment by juaneduardo** [comment]
I will check this right now... also I read that web2py updated all his ajax lib... 
I will push a new update soon...
