### ISSUE TITLE
Pre populate database

### ISSUE THREAD

**Issue by mabahamo** [poderopedia/plug-and-play-1.0-RC#6]
I have cloned the last version of Plug and Play 1.0 RC and i have problems setting up the database for the platform.

Steps:

1) Install web2py
2) cd web2py; rm -rf applications
3) git clone https://github.com/poderopedia/plug-and-play-1.0-RC applications
4) Modify settings at applications/admin/models/0.py:
settings.migrate = True
settings.database_uri = 'mysql://myuser:mypass@localhost/mydatabase'
5) Then i go to http://localhost:8000/admin or http://localhost:8000/admin/install

I have tested several combinations with the same result: Ubuntu 12.04 and Mac Os X 10.8 with Mysql 5.1, PostgreSQL 9.1 and Python 2.7

After perform this steps i'm always getting this message on applications/admin/errors:

S'"INSERT INTO auth_user(username,city,first_name,l...ps it. \',\'tomoduce@example.com\',\'Graig Groshek\');"'
p184
sS'self'
p185
S'<gluon.dal.PostgreSQLAdapter object>'
p186
sS'e'
S'ProgrammingError(\'ERROR\', \'23503\', \'insert or up...foreign key constraint "auth_user_country_fkey"\')'
p187
sS'fields'
p188
S"[(<gluon.dal.Field object>, 'rocky5445'), (<gluon.dal.Field object>, 'James matter exist in the floor of the sea. the behaviour. '), (<gluon.dal.Field object>, 'Hiroko'), (<gluon.dal.Field object>, 'Dinneen'), (<gluon.dal.Field object>, None), (<gluon.dal.Field object>, 'Successful. Huxley regarded as we are concerned chiefly in s'), (<gluon.dal.Field object>, 'Breach of the oval than an ether and moon showing a. '), (<gluon.dal.Field object>, 44), (<gluon.dal.Field object>, 'Weathered by the open sea.\nHe was too faint indi...ological proof of knowledge of the caterpillars.\n'), (<gluon.dal.Field object>, 'Pigments compounded of a great southward migration; and ever'), (<gluon.dal.Field object>, None), (<gluon.dal.Field object>, 'Beside it was no larger in which separates monkeys other spi'), (<gluon.dal.Field object>, datetime.datetime(2013, 6, 27, 15, 10, 25, 177807)), (<gluon.dal.Field object>, None), (<gluon.dal.Field object>, '1548 Alonzo Weerts Street'), (<gluon.dal.Field object>, datetime.datetime(2013, 6, 27, 15, 10, 25, 177807)), (<gluon.dal.Field object>, ''), (<gluon.dal.Field object>, 'Parachuting. If the egg signalling to be asked perhaps it. '), (<gluon.dal.Field object>, 'tomoduce@example.com'), (<gluon.dal.Field object>, 'Graig Groshek')]"
p189
sS'table'
p190
S'<Table auth_user (id,username,first_name,last_na...stration_key,reset_password_key,registration_id)>'
p191
sssS'traceback'
p192
S'Traceback (most recent call last):\n  File "web2py/gluon/restricted.py", line 212, in restricted\n    exec ccode in environment\n  File "web2py/applications/admin/models/db_wizard_populate.py", line 3, in <module>\n    populate(db.auth_user,10)\n  File "web2py/gluon/contrib/populate.py", line 104, in populate\n    table.insert(**record)\n  File "web2py/gluon/dal.py", line 8598, in insert\n    ret =  self._db._adapter.insert(self, self._listify(fields))\n  File "web2py/gluon/dal.py", line 1210, in insert\n    raise e\nProgrammingError: (\'ERROR\', \'23503\', \'insert or update on table "auth_user" violates foreign key constraint "auth_user_country_fkey"\')\n'

**Comment by juaneduardo** [comment]
I will check that inmediately.  auth_user.country fileld is required. Please,  can you check if the country table is populated

**Comment by mabahamo** [comment]
The country table is empty

**Comment by juaneduardo** [comment]
i will push a new update

**Comment by mabahamo** [comment]
I have updated to the new version but i am still getting some errors on the pre-populate database stage:

<type 'exceptions.ImportError'> cannot import name SetupPopulate"
p3
sS'layer'
p4
S' web2py/applications/admin/controllers/install.py'

The error log file is available on: http://pastebin.com/UYb3UsUm

The table 'Country' is still empty

**Comment by juaneduardo** [comment]
I will do some test... I see that install.py is not importing the module...  What is your OS to replicate the error?

**Comment by mabahamo** [comment]
Currently I'm using Mac OS X 10.8.4 and Python 2.7, but i also have access to another platforms. I could try with a different os if you like.

**Comment by juaneduardo** [comment]
mabahamo can you eliminate the *.pyc files from the modules/setup directory... and recheck please.

**Comment by mabahamo** [comment]
I did this with an empty MySQL database:

```
rm -rf applications
git clone https://github.com/poderopedia/plug-and-play-1.0-RC applications
find . -name "*.pyc" -exec rm -rf "{}" \;
```

modify settings.database_uri on applications/admin/models/0.py 
start the server:

```
python2.7 web2py.py
```

Then i open a browser: http://127.0.0.1:8000/admin and SUCCESS

Test with a mysql console:

```
mysql> select * from country;  
Empty set (0.00 sec)
```

Go to http://127.0.0.1:8000/admin/install and get INTERNAL ERROR. Full error log message on: http://pastebin.com/2h6uTqzU (cannot import name SetupPopulate)

Tried changing settings.migrate from True to False on applications/admin/models/0.py but i get the same error message.

**Comment by juaneduardo** [comment]
mabahamo can you reload the module or reboot webpy?

**Comment by mabahamo** [comment]
Ok, when i reboot web2py and i get the same error: cannot import name SetupPopulate.

I also tried stoping web2py, deleting the *.pyc files and then starting web2py but I get the same error.

**Comment by mabahamo** [comment]
Now its working.

Thanks.
