### ISSUE TITLE
'AutocompleteWidget' object has no attribute 'help_field'"

### ISSUE THREAD

**Issue by mabahamo** [poderopedia/plug-and-play-1.0-RC#7]
On a fresh new install i added two persons, then i try to stablish a relationship between them and i get this message: "An error ocurred, please reload the page".

If i reload the page, the error message appears again.

When i look the error log file, i get this:

```
(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'AutocompleteWidget' object has no attribute             'help_field'"
p3
sS'layer'
p4
S'/Users/mabahamo/Downloads/web2py/applications/admin/models/db.py'
```

Full error log message on: http://pastebin.com/d1G07ZmY

![screen shot 2013-07-03 at 1 41 41 pm](https://f.cloud.github.com/assets/547307/744950/1d21a398-e408-11e2-9b76-ba5a86b322a8.png)

**Comment by juaneduardo** [comment]
Is a problem with new version of web2py
https://groups.google.com/forum/#!topic/web2py/sC6XIuzWhGg
https://code.google.com/p/web2py/issues/detail?id=1565
was fixed June 11, 2013 in trunk
